<?php

declare(strict_types=1);

namespace Psalm\LaravelPlugin\Handlers\Eloquent\Metadata;

/**
 * Primary-key description reflecting trait overrides.
 *
 * For complete metadata, models using Laravel's unique-string-ID traits resolve to
 * `PrimaryKeyType::String` with `incrementing = false`. Incomplete metadata is ignored
 * by consumers in favor of the framework stubs.
 *
 * @psalm-immutable
 * @psalm-api
 * @internal
 */
final readonly class PrimaryKeyInfo
{
    /**
     * @param non-empty-string|null   $name        Primary-key column name (e.g. `id`). Null means the model has no
     *                                               usable single Eloquent key; its table may still have a composite key.
     * @param list<non-empty-string>  $uuidColumns Columns generated by `HasUniqueStringIds::uniqueIds()`.
     */
    public function __construct(
        public ?string $name,
        public PrimaryKeyType $type,
        public bool $incrementing,
        public array $uuidColumns,
    ) {}
}
