--FILE--
<?php declare(strict_types=1);

use App\Models\Customer;
use App\Models\Shop;

/**
 * @see https://github.com/psalm/psalm-plugin-laravel/issues/503
 *
 * Test that aggregate accessor properties generated by withCount(), withSum(), withMin(),
 * withMax(), withAvg(), and withExists() are recognised as valid magic properties
 * with the correct types.
 *
 * Alias naming convention (from Laravel's withAggregate()):
 *   Str::snake("{relation} {function} {column}")
 *
 * - withCount/withExists: column = '*' (stripped) → `{relation}_{function}`
 * - withMin/withMax/withSum/withAvg: column included → `{relation}_{function}_{column}`
 *
 * Uses App\Models\Shop for camelCase relation methods (work_orders → workOrders),
 * and App\Models\Customer for body-parsed and @property override cases.
 */

// --- withCount / loadCount: int ---
// alias: Str::snake("work_orders count *") = "work_orders_count"

function test_count_camelCase_relation(Shop $shop): int
{
    /** @psalm-check-type-exact $count = int */
    $count = $shop->work_orders_count;
    return $count;
}

function test_count_direct_relation(Shop $shop): int
{
    /** @psalm-check-type-exact $count = int */
    $count = $shop->parts_count;
    return $count;
}

function test_count_single_relation(Shop $shop): int
{
    /** @psalm-check-type-exact $count = int */
    $count = $shop->owner_count;
    return $count;
}

// --- withExists / loadExists: bool ---
// alias: Str::snake("work_orders exists *") = "work_orders_exists"

function test_exists_camelCase_relation(Shop $shop): bool
{
    /** @psalm-check-type-exact $exists = bool */
    $exists = $shop->work_orders_exists;
    return $exists;
}

function test_exists_single_relation(Shop $shop): bool
{
    /** @psalm-check-type-exact $exists = bool */
    $exists = $shop->owner_exists;
    return $exists;
}

// --- withMin / withMax / loadMin / loadMax: string|null ---
// alias: Str::snake("work_orders min price") = "work_orders_min_price"

function test_min_camelCase_relation(Shop $shop): string|null
{
    /** @psalm-check-type-exact $min = string|null */
    $min = $shop->work_orders_min_price;
    return $min;
}

function test_max_camelCase_relation(Shop $shop): string|null
{
    /** @psalm-check-type-exact $max = string|null */
    $max = $shop->work_orders_max_price;
    return $max;
}

// --- withSum / withAvg / loadSum / loadAvg: numeric-string|null ---
// alias: Str::snake("work_orders sum amount") = "work_orders_sum_amount"

function test_sum_camelCase_relation(Shop $shop): string|null
{
    /** @psalm-check-type-exact $sum = numeric-string|null */
    $sum = $shop->work_orders_sum_amount;
    return $sum;
}

function test_avg_camelCase_relation(Shop $shop): string|null
{
    /** @psalm-check-type-exact $avg = numeric-string|null */
    $avg = $shop->work_orders_avg_rating;
    return $avg;
}

// --- Snake-case method name (direct prefix match, no camelCase conversion needed) ---
// Shop::damage_reports() is named in snake_case, so `damage_reports_count` matches directly
// without going through snakeToCamelCase(). Exercises the first branch of isRelationPrefix().

function test_count_snake_named_relation(Shop $shop): int
{
    /** @psalm-check-type-exact $count = int */
    $count = $shop->damage_reports_count;
    return $count;
}

function test_sum_snake_named_relation(Shop $shop): string|null
{
    /** @psalm-check-type-exact $sum = numeric-string|null */
    $sum = $shop->damage_reports_sum_amount;
    return $sum;
}

// --- Multi-word column name (underscore in column) ---
// alias: Str::snake("work_orders min unit_price") = "work_orders_min_unit_price"
// Verifies the left-to-right strpos scan handles `_{suffix}_` inside a column name.

function test_min_multi_word_column(Shop $shop): string|null
{
    /** @psalm-check-type-exact $min = string|null */
    $min = $shop->work_orders_min_unit_price;
    return $min;
}

// --- Body-parsed relation method (no declared return type) ---
// Shop::supplierList() has no return type; the handler must parse the body AST.

function test_count_body_parsed_relation(Shop $shop): int
{
    /** @psalm-check-type-exact $count = int */
    $count = $shop->supplier_list_count;
    return $count;
}

function test_sum_body_parsed_relation(Shop $shop): string|null
{
    /** @psalm-check-type-exact $sum = numeric-string|null */
    $sum = $shop->supplier_list_sum_amount;
    return $sum;
}

// --- @property annotation overrides aggregate type ---
// Customer declares @property int<0, max> $vehicles_count which wins over the handler's int.

function test_property_annotation_overrides_aggregate_type(Customer $customer): int
{
    /** @psalm-check-type-exact $count = int<0, max> */
    $count = $customer->vehicles_count;
    return $count;
}
?>
--EXPECTF--
