<?php

declare(strict_types=1);

namespace Psalm\LaravelPlugin\Providers\ModelMetadata;

/**
 * Primary-key description reflecting trait overrides.
 *
 * Models using {@see \Illuminate\Database\Eloquent\Concerns\HasUuids} or
 * {@see \Illuminate\Database\Eloquent\Concerns\HasUlids} always resolve to
 * `PrimaryKeyType::String` with `incrementing = false`, regardless of the
 * base `$keyType` / `$incrementing` defaults.
 *
 * @psalm-immutable
 * @psalm-api
 * @internal
 */
final readonly class PrimaryKeyInfo
{
    /**
     * @param non-empty-string        $name        Primary-key column name (e.g. `id`).
     * @param list<non-empty-string>  $uuidColumns Columns generated by `HasUuids::uniqueIds()` (empty for non-UUID models).
     */
    public function __construct(
        public string $name,
        public PrimaryKeyType $type,
        public bool $incrementing,
        public array $uuidColumns,
    ) {}
}
