--FILE--
<?php declare(strict_types=1);

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Vite;

/**
 * Coverage for issue #899 idea #5: macros registered on a Macroable owner
 * (e.g. `Illuminate\Routing\Router`, `Illuminate\Http\Client\Factory`) must
 * also resolve when dispatched through the corresponding facade
 * (`Route::macroName()`, `Http::macroName()`).
 *
 * Macros are registered in `tests/Type/macro-fixtures.php`. The facade
 * propagation pass in `MacroHandler::afterCodebasePopulated()` consults
 * `FacadeMapProvider::getFacadeClasses()` and injects the same pseudo-methods
 * onto every facade class that proxies to the Macroable owner.
 */

function test_router_macro_resolves_via_facade_fqcn(): string
{
    $_ = Route::testRouterFacadeMacro('hello');
    /** @psalm-check-type-exact $_ = string */
    return $_;
}

function test_http_macro_resolves_via_facade_fqcn(): int
{
    $_ = Http::testHttpFacadeMacro('https://example.com');
    /** @psalm-check-type-exact $_ = int */
    return $_;
}

// Locks in https://laravel.com/docs/master/responses#response-macros
// (Response::macro registers on `Illuminate\Routing\ResponseFactory`, which
// the Response facade resolves to via `ResponseFactoryContract`).
function test_response_macro_resolves_via_facade_fqcn(): string
{
    $_ = Response::testResponseFacadeMacro('hi');
    /** @psalm-check-type-exact $_ = string */
    return $_;
}

// Locks in https://laravel.com/docs/master/vite#blade-aliases
// (Vite::macro registers on `Illuminate\Foundation\Vite`, which the Vite
// facade resolves to directly).
function test_vite_macro_resolves_via_facade_fqcn(): string
{
    $_ = Vite::testViteFacadeMacro('logo.svg');
    /** @psalm-check-type-exact $_ = string */
    return $_;
}

/**
 * Coverage for issue #899 idea #4 (multi-target facade dispatch).
 *
 * The fixtures register macros on the per-store concretes (`SessionGuard`,
 * `Repository`, etc.) that the Auth / Cache / Session / Storage / Mail facades
 * reach only via a non-Macroable manager's `__call` forwarding. Without the
 * multi-target seeding in `FacadeMapProvider::MULTI_TARGET_FACADES`, the
 * propagation pass never links the concrete back to the facade and these
 * calls surface as `UndefinedMagicMethod` errors.
 */
function test_auth_macro_via_session_guard_resolves_via_facade_fqcn(): string
{
    $_ = Auth::testAuthSessionGuardMacro('token');
    /** @psalm-check-type-exact $_ = string */
    return $_;
}

function test_auth_macro_via_request_guard_resolves_via_facade_fqcn(): int
{
    // Three concretes (SessionGuard, RequestGuard, TokenGuard) all propagate
    // to the same Auth facade. Every one must be visible — the array_merge
    // dedupe in `MacroHandler::afterCodebasePopulated()` keys by name and
    // these three macros have distinct names, so each gets its own pseudo-
    // method slot on the Auth facade storage.
    $_ = Auth::testAuthRequestGuardMacro('alice');
    /** @psalm-check-type-exact $_ = int */
    return $_;
}

function test_auth_macro_via_token_guard_resolves_via_facade_fqcn(): bool
{
    $_ = Auth::testAuthTokenGuardMacro('abc');
    /** @psalm-check-type-exact $_ = bool */
    return $_;
}

function test_cache_macro_resolves_via_facade_fqcn(): string
{
    $_ = Cache::testCacheFacadeMacro('user.1');
    /** @psalm-check-type-exact $_ = string */
    return $_;
}

function test_session_macro_resolves_via_facade_fqcn(): bool
{
    $_ = Session::testSessionFacadeMacro('locale');
    /** @psalm-check-type-exact $_ = bool */
    return $_;
}

function test_storage_macro_resolves_via_facade_fqcn(): int
{
    $_ = Storage::testStorageFacadeMacro('/uploads/avatar.png');
    /** @psalm-check-type-exact $_ = int */
    return $_;
}

function test_mail_macro_resolves_via_facade_fqcn(): string
{
    $_ = Mail::testMailFacadeMacro('user@example.com');
    /** @psalm-check-type-exact $_ = string */
    return $_;
}

function test_auth_macro_resolves_via_global_alias(): string
{
    // The multi-target seeding adds both the canonical FQCN and the global
    // alias (`Auth`) to `FacadeMapProvider`'s map, mirroring the single-target
    // alias-loader walk. Global alias dispatch must reach the macro just like
    // FQCN dispatch.
    $_ = \Auth::testAuthSessionGuardMacro('token');
    /** @psalm-check-type-exact $_ = string */
    return $_;
}

function test_router_macro_resolves_via_global_alias(): string
{
    // `\Route` is the global alias stub generated by `AliasStubProvider`,
    // declared as `class Route extends \Illuminate\Support\Facades\Route {}`.
    // The alias inherits pseudo-methods from its parent via the existing
    // `parent_classes` walk in `MacroHandler`, so resolution should match
    // the FQCN form above.
    $_ = \Route::testRouterFacadeMacro('hello');
    /** @psalm-check-type-exact $_ = string */
    return $_;
}

// The EXPECTF lines below render method names in lowercase
// (`testrouterfacademacro`, `testauthsessionguardmacro`) intentionally. Psalm
// keys pseudo-methods by lowercased name and that lowercased key is what
// `InvalidArgument` echoes back in the static-call path. Do NOT "fix" them to
// camelCase — they will cease to match the actual Psalm output and the test
// will fail.
//
// The Auth case below is non-redundant with the Route case: the Auth facade
// is the only row in `MULTI_TARGET_FACADES` whose injection map is built by
// `array_merge`-ing macro definitions from multiple concretes
// (SessionGuard + RequestGuard + TokenGuard, see
// `MacroHandler::afterCodebasePopulated()`). Argument validation must still
// fire correctly on the merged set; the Route case does not exercise that
// path because Route has a single concrete (Router).
function test_auth_macro_rejects_wrong_argument_type(): string
{
    return Auth::testAuthSessionGuardMacro(42);
}

function test_router_macro_rejects_wrong_argument_type(): string
{
    return Route::testRouterFacadeMacro(42);
}
?>
--EXPECTF--
InvalidArgument on line %d: Argument 1 of Illuminate\Support\Facades\Auth::testauthsessionguardmacro expects string, but 42 provided
InvalidArgument on line %d: Argument 1 of Illuminate\Support\Facades\Route::testrouterfacademacro expects string, but 42 provided
