--FILE--
<?php declare(strict_types=1);

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;

/**
 * Coverage for issue #899 idea #5: macros registered on a Macroable owner
 * (e.g. `Illuminate\Routing\Router`, `Illuminate\Http\Client\Factory`) must
 * also resolve when dispatched through the corresponding facade
 * (`Route::macroName()`, `Http::macroName()`).
 *
 * Macros are registered in `tests/Type/macro-fixtures.php`. The facade
 * propagation pass in `MacroHandler::afterCodebasePopulated()` consults
 * `FacadeMapProvider::getFacadeClasses()` and injects the same pseudo-methods
 * onto every facade class that proxies to the Macroable owner.
 */

function test_router_macro_resolves_via_facade_fqcn(): string
{
    $_ = Route::testRouterFacadeMacro('hello');
    /** @psalm-check-type-exact $_ = string */
    return $_;
}

function test_http_macro_resolves_via_facade_fqcn(): int
{
    $_ = Http::testHttpFacadeMacro('https://example.com');
    /** @psalm-check-type-exact $_ = int */
    return $_;
}

function test_router_macro_resolves_via_global_alias(): string
{
    // `\Route` is the global alias stub generated by `AliasStubProvider`,
    // declared as `class Route extends \Illuminate\Support\Facades\Route {}`.
    // The alias inherits pseudo-methods from its parent via the existing
    // `parent_classes` walk in `MacroHandler`, so resolution should match
    // the FQCN form above.
    $_ = \Route::testRouterFacadeMacro('hello');
    /** @psalm-check-type-exact $_ = string */
    return $_;
}

function test_router_macro_rejects_wrong_argument_type(): string
{
    return Route::testRouterFacadeMacro(42);
}
?>
--EXPECTF--
InvalidArgument on line %d: Argument 1 of Illuminate\Support\Facades\Route::testrouterfacademacro expects string, but 42 provided
