<?php

declare(strict_types=1);

namespace Psalm\LaravelPlugin\Handlers\Eloquent;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\Relation;
use Psalm\Codebase;
use Psalm\LaravelPlugin\Handlers\Eloquent\Metadata\ModelMetadata;
use Psalm\LaravelPlugin\Handlers\Eloquent\Metadata\ModelMetadataRegistry;
use Psalm\LaravelPlugin\Handlers\Eloquent\Metadata\RelationInfo;
use Psalm\LaravelPlugin\Handlers\Eloquent\Support\AggregateCallParser;
use Psalm\LaravelPlugin\Handlers\Eloquent\Support\RelationResolver;
use Psalm\Plugin\EventHandler\Event\PropertyExistenceProviderEvent;
use Psalm\Plugin\EventHandler\Event\PropertyTypeProviderEvent;
use Psalm\Plugin\EventHandler\Event\PropertyVisibilityProviderEvent;
use Psalm\StatementsSource;
use Psalm\Type;
use Psalm\Type\Atomic;
use Psalm\Type\Atomic\TBool;
use Psalm\Type\Atomic\TFloat;
use Psalm\Type\Atomic\TInt;
use Psalm\Type\Atomic\TIntRange;
use Psalm\Type\Atomic\TNamedObject;
use Psalm\Type\Atomic\TNull;
use Psalm\Type\Atomic\TNumericString;
use Psalm\Type\Atomic\TString;
use Psalm\Type\Union;

/**
 * Resolves Eloquent aggregate accessor properties generated by withCount(), withSum(),
 * withMin(), withMax(), withAvg(), and withExists() (and their loadXxx() counterparts).
 *
 * Laravel's withAggregate() builds the attribute alias via:
 *   Str::snake(preg_replace('/[^[:alnum:][:space:]_]/u', '', "{$relation} {$function} {$column}"))
 *
 * For withCount/withExists, the column is '*' which is stripped, yielding `{relation}_{function}`.
 * For withMin/withMax/withSum/withAvg, the column is included: `{relation}_{function}_{column}`.
 *
 * | Method       | Example alias              | Suffix match     | Unproven (default)                         | Proven loaded |
 * |--------------|----------------------------|------------------|--------------------------------------------|---------------|
 * | withCount    | contacts_count             | ends with _count | int|null                                   | int<0, max>   |
 * | withExists   | contacts_exists            | ends with _exists| bool|null                                  | bool          |
 * | withMin/Max  | contacts_max_amount        | contains _max_   | string|null (int column: int|null)           | same          |
 * | withSum      | contacts_sum_amount        | contains _sum_   | int|float|numeric-string|null (see below)  | same          |
 * | withAvg      | contacts_avg_amount        | contains _avg_   | float|numeric-string|null                  | same          |
 *
 * Unproven means nothing shows the aggregate was loaded: the attribute is absent (read as null)
 * until withXxx()/loadXxx() runs, so `$model->x_count ?? ...` is a legitimate guard. Proof comes from
 * a model `$withCount` default (this class) or from a literal withXxx()/loadXxx() call that
 * {@see ModelAggregateLoadHandler} tracks. min/max/sum/avg stay nullable even when proven (SQL NULL
 * for an empty relation).
 *
 * min/max/sum/avg are column-aware: the aggregated column of the RELATED model is resolved from the
 * migration schema ONLY, never casts or `@property` (Laravel does not cast aggregate aliases except
 * `exists`, so a datetime column stays a string). The schema maps DECIMAL to float, but PDO returns
 * DECIMAL as a string (and MySQL's SUM/AVG over exact values is DECIMAL) and SQLite returns integral
 * NUMERIC values as int, so min/max/sum over a float column also admit int and numeric-string:
 *
 * | Column | min / max                    | sum                          | avg                     |
 * |--------|------------------------------|------------------------------|-------------------------|
 * | int    | the int type|null            | int|numeric-string|null       | float|numeric-string|null |
 * | float  | int|float|numeric-string|null | int|float|numeric-string|null | float|numeric-string|null |
 * | other  | string|null                  | int|float|numeric-string|null | float|numeric-string|null |
 *
 * @see https://laravel.com/docs/eloquent-relationships#other-aggregate-functions
 * @see https://github.com/psalm/psalm-plugin-laravel/issues/503
 *
 * @internal
 */
final class ModelAggregatePropertyHandler
{
    /**
     * Suffixes whose alias has NO column component (column = '*', stripped by preg_replace).
     * Matched at the end of the property name: e.g. `contacts_count`.
     *
     * @var list<string>
     */
    private const EXACT_SUFFIXES = ['count', 'exists'];

    /**
     * Suffixes whose alias INCLUDES the column name (e.g. `contacts_sum_amount`).
     * Matched as `_{suffix}_` anywhere in the property name, with the relation prefix before it.
     *
     * @var list<string>
     */
    private const COLUMN_SUFFIXES = ['min', 'max', 'sum', 'avg'];

    /** @var array<string, bool> Cache for hasUserPseudoProperty(), keyed by "class::$property" */
    private static array $pseudoPropertyCache = [];

    /**
     * @var array<string, array{'count'|'exists'|'sum'|'min'|'max'|'avg', string, string, bool}|null>
     *     Cache for parseAggregateProperty(), keyed by "class::property" → [function, relation method,
     *     column ('' for count/exists), proven by a `$withCount` default] or null
     */
    private static array $matchCache = [];

    /** @var array<string, array<string, string>> `$withCount` default alias → relation name */
    private static array $defaultAliasCache = [];

    /**
     * @var array<string, bool> Cache for isRelationMethod(), keyed by "class::method".
     *                           Prevents redundant getMethodReturnType() calls when the same
     *                           relation is referenced by multiple aggregate properties.
     */
    private static array $relationMethodCache = [];

    /**
     * @var array<string, Union> Cached count/exists Union instances, keyed by "function" or
     *                            "function+" when proven loaded, to avoid repeated allocation.
     */
    private static array $typeCache = [];

    public static function reset(): void
    {
        self::$pseudoPropertyCache = [];
        self::$matchCache = [];
        self::$defaultAliasCache = [];
        self::$relationMethodCache = [];
    }

    public static function doesPropertyExist(PropertyExistenceProviderEvent $event): ?bool
    {
        if (!$event->isReadMode()) {
            return null;
        }

        $propertyName = $event->getPropertyName();

        $fqClasslikeName = $event->getFqClasslikeName();

        // Fast pre-check: bail before any codebase calls for the vast majority of
        // property accesses that can't possibly match an aggregate pattern.
        if (!self::couldBeAggregate($propertyName) && !isset(self::defaultAliases($fqClasslikeName)[$propertyName])) {
            return null;
        }

        $source = $event->getSource();
        if (!$source instanceof StatementsSource) {
            return null;
        }

        $codebase = $source->getCodebase();

        if (self::hasUserPseudoProperty($codebase, $fqClasslikeName, $propertyName)) {
            return null;
        }

        if (self::parseAggregateProperty($codebase, $fqClasslikeName, $propertyName) !== null) {
            return true;
        }

        return null;
    }

    public static function isPropertyVisible(PropertyVisibilityProviderEvent $event): ?bool
    {
        // PropertyVisibilityProviderEvent::getSource() is non-nullable, unlike the other events.
        if (!$event->isReadMode()) {
            return null;
        }

        $propertyName = $event->getPropertyName();
        $fqClasslikeName = $event->getFqClasslikeName();

        // Fast path: use cached match from doesPropertyExist() if available.
        $cacheKey = $fqClasslikeName . '::' . $propertyName;
        if (\array_key_exists($cacheKey, self::$matchCache)) {
            return self::$matchCache[$cacheKey] !== null ? true : null;
        }

        if (!self::couldBeAggregate($propertyName) && !isset(self::defaultAliases($fqClasslikeName)[$propertyName])) {
            return null;
        }

        $codebase = $event->getSource()->getCodebase();

        if (self::hasUserPseudoProperty($codebase, $fqClasslikeName, $propertyName)) {
            return null;
        }

        if (self::parseAggregateProperty($codebase, $fqClasslikeName, $propertyName) !== null) {
            return true;
        }

        return null;
    }

    public static function getPropertyType(PropertyTypeProviderEvent $event): ?Union
    {
        if (!$event->isReadMode()) {
            return null;
        }

        $source = $event->getSource();
        if (!$source instanceof StatementsSource) {
            return null;
        }

        $propertyName = $event->getPropertyName();
        $fqClasslikeName = $event->getFqClasslikeName();

        // A cached match means doesPropertyExist()/isPropertyVisible() already ruled out a user @property.
        $cacheKey = $fqClasslikeName . '::' . $propertyName;
        if (!\array_key_exists($cacheKey, self::$matchCache)) {
            if (!self::couldBeAggregate($propertyName) && !isset(self::defaultAliases($fqClasslikeName)[$propertyName])) {
                return null;
            }

            if (self::hasUserPseudoProperty($source->getCodebase(), $fqClasslikeName, $propertyName)) {
                return null;
            }
        }

        $codebase = $source->getCodebase();
        $match = self::parseAggregateProperty($codebase, $fqClasslikeName, $propertyName);
        if ($match === null) {
            return null;
        }

        [$function, $relation, $column, $proven] = $match;

        return self::aggregateType($codebase, $function, $fqClasslikeName, $relation, $column, $proven);
    }

    /**
     * Fast pre-check: returns true if the property name contains a pattern that could
     * match an aggregate accessor. This avoids any codebase lookups for properties
     * like `email` or `name` that are clearly not aggregates.
     *
     * @psalm-pure
     */
    private static function couldBeAggregate(string $propertyName): bool
    {
        foreach (self::EXACT_SUFFIXES as $suffix) {
            if (\str_ends_with($propertyName, '_' . $suffix)) {
                return true;
            }
        }

        foreach (self::COLUMN_SUFFIXES as $suffix) {
            if (\str_contains($propertyName, '_' . $suffix . '_')) {
                return true;
            }
        }

        return false;
    }

    /**
     * Parse an aggregate property name into [function, relation method, column, proven], or null
     * when it does not correspond to an aggregate accessor on this model.
     *
     * @return array{'count'|'exists'|'sum'|'min'|'max'|'avg', string, string, bool}|null
     */
    private static function parseAggregateProperty(
        Codebase $codebase,
        string $fqClasslikeName,
        string $propertyName,
    ): ?array {
        $cacheKey = $fqClasslikeName . '::' . $propertyName;

        if (\array_key_exists($cacheKey, self::$matchCache)) {
            return self::$matchCache[$cacheKey];
        }

        $result = self::doParseAggregateProperty($codebase, $fqClasslikeName, $propertyName);
        self::$matchCache[$cacheKey] = $result;

        return $result;
    }

    /**
     * Core matching logic for parseAggregateProperty().
     *
     * Three matching strategies:
     *
     * 0. A `$withCount` default (`rel` or `rel as alias`) whose alias is this property: the count is
     *    loaded by every query on the model, so the match is `proven`. Alias names need no suffix.
     *
     * 1. Exact suffix (count, exists): property ends with `_{suffix}`.
     *    The relation prefix is everything before `_{suffix}`.
     *
     * 2. Column-including suffix (min, max, sum, avg): property contains `_{suffix}_`.
     *    The relation prefix is everything before `_{suffix}_`; the column follows.
     *    Multiple `_{suffix}_` occurrences are tried left-to-right until a relation match
     *    is found (handles relation names that themselves contain the suffix word, and
     *    column names containing underscores, e.g. `contacts_min_unit_price`).
     *
     * @return array{'count'|'exists'|'sum'|'min'|'max'|'avg', string, string, bool}|null
     */
    private static function doParseAggregateProperty(
        Codebase $codebase,
        string $fqClasslikeName,
        string $propertyName,
    ): ?array {
        $defaultRelation = self::defaultAliases($fqClasslikeName)[$propertyName] ?? null;
        if ($defaultRelation !== null && self::isRelationMethod($codebase, $fqClasslikeName, $defaultRelation)) {
            return ['count', $defaultRelation, '', true];
        }

        // Strategy 1: withCount/withExists — alias is {relation}_{suffix}, no column in name.
        foreach (self::EXACT_SUFFIXES as $suffix) {
            if (!\str_ends_with($propertyName, '_' . $suffix)) {
                continue;
            }

            $prefix = \substr($propertyName, 0, -\strlen($suffix) - 1);
            $relation = $prefix === '' ? null : self::resolveRelationPrefix($codebase, $fqClasslikeName, $prefix);
            if ($relation !== null) {
                return [$suffix, $relation, '', false];
            }
        }

        // Strategy 2: withMin/withMax/withSum/withAvg — alias is {relation}_{suffix}_{column}.
        // Search for `_{suffix}_` in the property name; the prefix before it is the relation.
        foreach (self::COLUMN_SUFFIXES as $suffix) {
            $needle = '_' . $suffix . '_';
            $pos = 0;

            while (($pos = \strpos($propertyName, $needle, $pos)) !== false) {
                $pos++;
                if ($pos === 1) {
                    // needle at position 0 — no relation prefix possible
                    continue;
                }

                $relation = self::resolveRelationPrefix($codebase, $fqClasslikeName, \substr($propertyName, 0, $pos - 1));
                if ($relation !== null) {
                    return [$suffix, $relation, \substr($propertyName, $pos - 1 + \strlen($needle)), false];
                }
            }
        }

        return null;
    }

    /**
     * `$withCount` defaults of the model as alias → relation name. Optimistic like column
     * inference: a default that runtime code bypasses (`new Model`, `withoutGlobalScopes`-style
     * raw queries) still reads as loaded. Not cached before the registry entry exists, since
     * property providers may fire before warm-up.
     *
     * @return array<string, string>
     */
    private static function defaultAliases(string $fqClasslikeName): array
    {
        if (isset(self::$defaultAliasCache[$fqClasslikeName])) {
            return self::$defaultAliasCache[$fqClasslikeName];
        }

        /** @var class-string<Model> $fqClasslikeName registered per Model subclass */
        $metadata = ModelMetadataRegistry::for($fqClasslikeName);
        if (!$metadata instanceof ModelMetadata) {
            return [];
        }

        $aliases = [];

        if ($metadata->isComplete(ModelMetadata::SECTION_RUNTIME_CONFIGURATION)) {
            foreach ($metadata->withCount as $entry) {
                [$relation, $alias] = AggregateCallParser::splitAlias($entry);
                $aliases[$alias ?? AggregateCallParser::defaultAlias($relation, 'count', '*')] = $relation;
            }
        }

        return self::$defaultAliasCache[$fqClasslikeName] = $aliases;
    }

    /**
     * Resolve the given snake_case prefix to the relation method it names, or null.
     *
     * Tries the prefix directly (for snake_case method names) and then its camelCase
     * equivalent (for typical camelCase methods like `workOrders`).
     */
    private static function resolveRelationPrefix(Codebase $codebase, string $fqClasslikeName, string $prefix): ?string
    {
        if (self::isRelationMethod($codebase, $fqClasslikeName, $prefix)) {
            return $prefix;
        }

        $camelPrefix = self::snakeToCamelCase($prefix);

        return $camelPrefix !== $prefix && self::isRelationMethod($codebase, $fqClasslikeName, $camelPrefix)
            ? $camelPrefix
            : null;
    }

    /**
     * Determine whether the method at `{fqClasslikeName}::{methodName}` is a relation method.
     *
     * Mirrors ModelRelationshipPropertyHandler::relationExists() — accepts both generic and
     * non-generic Relation return types, and falls back to body parsing for untyped methods.
     * Results are cached to avoid redundant codebase lookups across multiple aggregate
     * properties sharing the same relation (e.g. contacts_count and contacts_sum_amount).
     */
    public static function isRelationMethod(Codebase $codebase, string $fqClasslikeName, string $methodName): bool
    {
        $key = $fqClasslikeName . '::' . $methodName;

        if (\array_key_exists($key, self::$relationMethodCache)) {
            return self::$relationMethodCache[$key];
        }

        if (!$codebase->methodExists($key)) {
            return self::$relationMethodCache[$key] = false;
        }

        // getMethodReturnType() takes $self_class by reference and may set it to null,
        // so use a disposable copy to protect $fqClasslikeName.
        $selfClass = $fqClasslikeName;
        try {
            $returnType = $codebase->getMethodReturnType($key, $selfClass);
        } catch (\InvalidArgumentException|\UnexpectedValueException|\RuntimeException $e) {
            $codebase->progress->debug("Laravel plugin: could not get return type for {$key}: {$e->getMessage()}\n");
            return self::$relationMethodCache[$key] = false;
        }

        if ($returnType instanceof Union) {
            foreach ($returnType->getAtomicTypes() as $type) {
                if ($type instanceof TNamedObject && \is_a($type->value, Relation::class, true)) {
                    return self::$relationMethodCache[$key] = true;
                }
            }

            return self::$relationMethodCache[$key] = false;
        }

        // No return type declared — check the registry's pre-parsed OWN-CLASS relations for a factory
        // call (the precomputed equivalent of RelationMethodParser::parse() with the same own-class
        // resolution, mirroring ModelRelationshipPropertyHandler::registryRelation()).
        /** @var class-string<Model> $fqClasslikeName registered per Model subclass */
        $relation = ModelMetadataRegistry::for($fqClasslikeName)?->relations()[\strtolower($methodName)] ?? null;
        return self::$relationMethodCache[$key] = $relation instanceof RelationInfo;
    }

    /**
     * The attribute type of an aggregate on `$model`'s relation. `$proven` means the code shows the
     * aggregate was loaded; it only tightens count/exists, because min/max/sum/avg are NULL on an
     * empty relation either way.
     *
     * Types match Laravel's raw database output before any model casts are applied (only `exists`
     * is cast, to bool). Count/exists results are cached to avoid repeated allocation.
     *
     * @param 'count'|'exists'|'sum'|'min'|'max'|'avg' $function
     */
    public static function aggregateType(
        Codebase $codebase,
        string $function,
        string $model,
        string $relation,
        string $column,
        bool $proven,
    ): Union {
        if ($function === 'count' || $function === 'exists') {
            $key = $function . ($proven ? '+' : '');
            if (isset(self::$typeCache[$key])) {
                return self::$typeCache[$key];
            }

            $loaded = $function === 'exists' ? new TBool() : ($proven ? new TIntRange(0, null) : new TInt());

            return self::$typeCache[$key] = new Union($proven ? [$loaded] : [$loaded, new TNull()]);
        }

        /** @var class-string<Model>|null $related */
        $related = RelationResolver::relatedModel($codebase, $model, $relation);

        return self::columnAwareType(
            $function,
            $related === null ? null : ModelPropertyHandler::resolveRawColumnType($related, $column),
        );
    }

    /**
     * min/max/sum/avg type from the aggregated column's RAW schema type (null when unresolvable).
     * Always nullable: SQL NULL for an empty relation.
     *
     * The schema maps DECIMAL to float, yet PDO returns DECIMAL as a string and MySQL's SUM/AVG
     * over exact values is DECIMAL and SQLite returns integral NUMERIC values as int, so min/max/sum
     * over a float column admit int and numeric-string (AVG is always a real or DECIMAL); SUM over an
     * int column is int on SQLite/PostgreSQL-bigint but DECIMAL (string) on MySQL.
     *
     * @param 'sum'|'min'|'max'|'avg' $function
     * @psalm-external-mutation-free
     */
    public static function columnAwareType(string $function, ?Union $rawColumnType): Union
    {
        $shape = $rawColumnType instanceof Union ? BuilderAggregateHandler::numericShape($rawColumnType) : null;
        /** @var non-empty-list<Atomic> $atoms */
        $atoms = match ($function) {
            'avg' => [new TFloat(), new TNumericString()],
            'sum' => match ($shape) {
                'int' => [new TInt(), new TNumericString()],
                default => [new TInt(), new TFloat(), new TNumericString()],
            },
            'min', 'max' => match ($shape) {
                'int' => \array_values($rawColumnType?->getAtomicTypes() ?? []),
                'float' => [new TInt(), new TFloat(), new TNumericString()],
                default => [new TString()],
            },
        };

        return Type::combineUnionTypes(new Union($atoms), Type::getNull());
    }

    /**
     * Convert a snake_case string to camelCase.
     *
     * `work_orders` → `workOrders`
     *
     * @psalm-pure
     */
    private static function snakeToCamelCase(string $value): string
    {
        return \lcfirst(\str_replace('_', '', \ucwords($value, '_')));
    }

    /**
     * Check whether the user has declared a @property PHPDoc for this property.
     * If so, we defer to their declaration instead of providing an aggregate type.
     */
    public static function hasUserPseudoProperty(
        Codebase $codebase,
        string $fqClasslikeName,
        string $propertyName,
    ): bool {
        $key = $fqClasslikeName . '::$' . $propertyName;

        if (\array_key_exists($key, self::$pseudoPropertyCache)) {
            return self::$pseudoPropertyCache[$key];
        }

        if (!$codebase->classlike_storage_provider->has($fqClasslikeName)) {
            return self::$pseudoPropertyCache[$key] = false;
        }

        $classStorage = $codebase->classlike_storage_provider->get($fqClasslikeName);
        $result = isset($classStorage->pseudo_property_get_types['$' . $propertyName]);
        return self::$pseudoPropertyCache[$key] = $result;
    }
}
