<?php

declare(strict_types=1);

namespace Psalm\LaravelPlugin\Handlers\Eloquent;

use Illuminate\Database\Eloquent\Relations\Relation;
use Psalm\Codebase;
use Psalm\Plugin\EventHandler\Event\PropertyExistenceProviderEvent;
use Psalm\Plugin\EventHandler\Event\PropertyTypeProviderEvent;
use Psalm\Plugin\EventHandler\Event\PropertyVisibilityProviderEvent;
use Psalm\StatementsSource;
use Psalm\Type\Atomic\TBool;
use Psalm\Type\Atomic\TInt;
use Psalm\Type\Atomic\TNamedObject;
use Psalm\Type\Atomic\TNull;
use Psalm\Type\Atomic\TNumericString;
use Psalm\Type\Atomic\TString;
use Psalm\Type\Union;

/**
 * Resolves Eloquent aggregate accessor properties generated by withCount(), withSum(),
 * withMin(), withMax(), withAvg(), and withExists() (and their loadXxx() counterparts).
 *
 * Laravel's withAggregate() builds the attribute alias via:
 *   Str::snake(preg_replace('/[^[:alnum:][:space:]_]/u', '', "{$relation} {$function} {$column}"))
 *
 * For withCount/withExists, the column is '*' which is stripped, yielding `{relation}_{function}`.
 * For withMin/withMax/withSum/withAvg, the column is included: `{relation}_{function}_{column}`.
 *
 * | Method       | Example alias              | Suffix match              | Type                |
 * |--------------|----------------------------|---------------------------|---------------------|
 * | withCount    | contacts_count             | ends with _count          | int                 |
 * | withExists   | contacts_exists            | ends with _exists         | bool                |
 * | withMin      | contacts_min_amount        | contains _min_            | string|null         |
 * | withMax      | contacts_max_amount        | contains _max_            | string|null         |
 * | withSum      | contacts_sum_amount        | contains _sum_            | numeric-string|null |
 * | withAvg      | contacts_avg_amount        | contains _avg_            | numeric-string|null |
 *
 * @see https://laravel.com/docs/eloquent-relationships#other-aggregate-functions
 * @see https://github.com/psalm/psalm-plugin-laravel/issues/503
 *
 * @internal
 */
final class ModelAggregatePropertyHandler
{
    /**
     * Suffixes whose alias has NO column component (column = '*', stripped by preg_replace).
     * Matched at the end of the property name: e.g. `contacts_count`.
     *
     * @var list<string>
     */
    private const EXACT_SUFFIXES = ['count', 'exists'];

    /**
     * Suffixes whose alias INCLUDES the column name (e.g. `contacts_sum_amount`).
     * Matched as `_{suffix}_` anywhere in the property name, with the relation prefix before it.
     *
     * @var list<string>
     */
    private const COLUMN_SUFFIXES = ['min', 'max', 'sum', 'avg'];

    /** @var array<string, bool> Cache for hasUserPseudoProperty(), keyed by "class::$property" */
    private static array $pseudoPropertyCache = [];

    /**
     * @var array<string, string|null> Cache for parseAggregateProperty(),
     *                                  keyed by "class::property" → suffix string or null
     */
    private static array $suffixCache = [];

    /**
     * @var array<string, bool> Cache for isRelationMethod(), keyed by "class::method".
     *                           Prevents redundant getMethodReturnType() calls when the same
     *                           relation is referenced by multiple aggregate properties.
     */
    private static array $relationMethodCache = [];

    /**
     * @var array<string, Union> Cached Union instances for each aggregate suffix,
     *                            to avoid repeated allocation across analysis runs.
     */
    private static array $typeCache = [];

    public static function doesPropertyExist(PropertyExistenceProviderEvent $event): ?bool
    {
        if (! $event->isReadMode()) {
            return null;
        }

        $propertyName = $event->getPropertyName();

        // Fast pre-check: bail before any codebase calls for the vast majority of
        // property accesses that can't possibly match an aggregate pattern.
        if (! self::couldBeAggregate($propertyName)) {
            return null;
        }

        $source = $event->getSource();
        if (! $source instanceof StatementsSource) {
            return null;
        }

        $codebase = $source->getCodebase();
        $fqClasslikeName = $event->getFqClasslikeName();

        if (self::hasUserPseudoProperty($codebase, $fqClasslikeName, $propertyName)) {
            return null;
        }

        if (self::parseAggregateProperty($codebase, $fqClasslikeName, $propertyName) !== null) {
            return true;
        }

        return null;
    }

    public static function isPropertyVisible(PropertyVisibilityProviderEvent $event): ?bool
    {
        // PropertyVisibilityProviderEvent::getSource() is non-nullable, unlike the other events.
        if (! $event->isReadMode()) {
            return null;
        }

        $propertyName = $event->getPropertyName();
        $fqClasslikeName = $event->getFqClasslikeName();

        // Fast path: use cached suffix from doesPropertyExist() if available.
        $cacheKey = $fqClasslikeName . '::' . $propertyName;
        if (\array_key_exists($cacheKey, self::$suffixCache)) {
            return self::$suffixCache[$cacheKey] !== null ? true : null;
        }

        if (! self::couldBeAggregate($propertyName)) {
            return null;
        }

        $codebase = $event->getSource()->getCodebase();

        if (self::hasUserPseudoProperty($codebase, $fqClasslikeName, $propertyName)) {
            return null;
        }

        if (self::parseAggregateProperty($codebase, $fqClasslikeName, $propertyName) !== null) {
            return true;
        }

        return null;
    }

    public static function getPropertyType(PropertyTypeProviderEvent $event): ?Union
    {
        if (! $event->isReadMode()) {
            return null;
        }

        $propertyName = $event->getPropertyName();
        $fqClasslikeName = $event->getFqClasslikeName();

        // Fast path: use cached suffix from doesPropertyExist()/isPropertyVisible() if available.
        $cacheKey = $fqClasslikeName . '::' . $propertyName;
        if (\array_key_exists($cacheKey, self::$suffixCache)) {
            $suffix = self::$suffixCache[$cacheKey];
            return $suffix !== null ? self::buildTypeForSuffix($suffix) : null;
        }

        if (! self::couldBeAggregate($propertyName)) {
            return null;
        }

        $source = $event->getSource();
        if (! $source instanceof StatementsSource) {
            return null;
        }

        $codebase = $source->getCodebase();

        if (self::hasUserPseudoProperty($codebase, $fqClasslikeName, $propertyName)) {
            return null;
        }

        $suffix = self::parseAggregateProperty($codebase, $fqClasslikeName, $propertyName);
        if ($suffix === null) {
            return null;
        }

        return self::buildTypeForSuffix($suffix);
    }

    /**
     * Fast pre-check: returns true if the property name contains a pattern that could
     * match an aggregate accessor. This avoids any codebase lookups for properties
     * like `email` or `name` that are clearly not aggregates.
     *
     * @psalm-pure
     */
    private static function couldBeAggregate(string $propertyName): bool
    {
        foreach (self::EXACT_SUFFIXES as $suffix) {
            if (\str_ends_with($propertyName, '_' . $suffix)) {
                return true;
            }
        }

        foreach (self::COLUMN_SUFFIXES as $suffix) {
            if (\str_contains($propertyName, '_' . $suffix . '_')) {
                return true;
            }
        }

        return false;
    }

    /**
     * Parse an aggregate property name and return its aggregate suffix if valid.
     *
     * Returns the matched suffix (e.g. 'count', 'sum'), or null if the property
     * does not correspond to an aggregate accessor on this model.
     */
    private static function parseAggregateProperty(Codebase $codebase, string $fqClasslikeName, string $propertyName): ?string
    {
        $cacheKey = $fqClasslikeName . '::' . $propertyName;

        if (\array_key_exists($cacheKey, self::$suffixCache)) {
            return self::$suffixCache[$cacheKey];
        }

        $result = self::doParseAggregateProperty($codebase, $fqClasslikeName, $propertyName);
        self::$suffixCache[$cacheKey] = $result;

        return $result;
    }

    /**
     * Core matching logic for parseAggregateProperty().
     *
     * Two matching strategies based on whether the alias includes the column name:
     *
     * 1. Exact suffix (count, exists): property ends with `_{suffix}`.
     *    The relation prefix is everything before `_{suffix}`.
     *
     * 2. Column-including suffix (min, max, sum, avg): property contains `_{suffix}_`.
     *    The relation prefix is everything before `_{suffix}_`; the column follows.
     *    Multiple `_{suffix}_` occurrences are tried left-to-right until a relation match
     *    is found (handles relation names that themselves contain the suffix word, and
     *    column names containing underscores, e.g. `contacts_min_unit_price`).
     */
    private static function doParseAggregateProperty(Codebase $codebase, string $fqClasslikeName, string $propertyName): ?string
    {
        // Strategy 1: withCount/withExists — alias is {relation}_{suffix}, no column in name.
        foreach (self::EXACT_SUFFIXES as $suffix) {
            if (! \str_ends_with($propertyName, '_' . $suffix)) {
                continue;
            }

            $prefix = \substr($propertyName, 0, -\strlen($suffix) - 1);
            if ($prefix !== '' && self::isRelationPrefix($codebase, $fqClasslikeName, $prefix)) {
                return $suffix;
            }
        }

        // Strategy 2: withMin/withMax/withSum/withAvg — alias is {relation}_{suffix}_{column}.
        // Search for `_{suffix}_` in the property name; the prefix before it is the relation.
        foreach (self::COLUMN_SUFFIXES as $suffix) {
            $needle = '_' . $suffix . '_';
            $pos = 0;

            while (($pos = \strpos($propertyName, $needle, $pos)) !== false) {
                $pos++;
                if ($pos === 1) {
                    // needle at position 0 — no relation prefix possible
                    continue;
                }

                $prefix = \substr($propertyName, 0, $pos - 1);
                if (self::isRelationPrefix($codebase, $fqClasslikeName, $prefix)) {
                    return $suffix;
                }
            }
        }

        return null;
    }

    /**
     * Check whether the given snake_case prefix maps to a relation method on this model.
     *
     * Tries the prefix directly (for snake_case method names) and then its camelCase
     * equivalent (for typical camelCase methods like `workOrders`).
     */
    private static function isRelationPrefix(Codebase $codebase, string $fqClasslikeName, string $prefix): bool
    {
        if (self::isRelationMethod($codebase, $fqClasslikeName, $prefix)) {
            return true;
        }

        $camelPrefix = self::snakeToCamelCase($prefix);
        return $camelPrefix !== $prefix && self::isRelationMethod($codebase, $fqClasslikeName, $camelPrefix);
    }

    /**
     * Determine whether the method at `{fqClasslikeName}::{methodName}` is a relation method.
     *
     * Mirrors ModelRelationshipPropertyHandler::relationExists() — accepts both generic and
     * non-generic Relation return types, and falls back to body parsing for untyped methods.
     * Results are cached to avoid redundant codebase lookups across multiple aggregate
     * properties sharing the same relation (e.g. contacts_count and contacts_sum_amount).
     */
    private static function isRelationMethod(Codebase $codebase, string $fqClasslikeName, string $methodName): bool
    {
        $key = $fqClasslikeName . '::' . $methodName;

        if (\array_key_exists($key, self::$relationMethodCache)) {
            return self::$relationMethodCache[$key];
        }

        if (! $codebase->methodExists($key)) {
            return self::$relationMethodCache[$key] = false;
        }

        // getMethodReturnType() takes $self_class by reference and may set it to null,
        // so use a disposable copy to protect $fqClasslikeName.
        $selfClass = $fqClasslikeName;
        try {
            $returnType = $codebase->getMethodReturnType($key, $selfClass);
        } catch (\InvalidArgumentException|\UnexpectedValueException|\RuntimeException $e) {
            $codebase->progress->debug("Laravel plugin: could not get return type for {$key}: {$e->getMessage()}\n");
            return self::$relationMethodCache[$key] = false;
        }

        if ($returnType instanceof Union) {
            foreach ($returnType->getAtomicTypes() as $type) {
                if ($type instanceof TNamedObject && \is_a($type->value, Relation::class, true)) {
                    return self::$relationMethodCache[$key] = true;
                }
            }

            return self::$relationMethodCache[$key] = false;
        }

        // No return type declared — check the method body for relationship factory calls.
        $result = RelationMethodParser::parse($codebase, $fqClasslikeName, $methodName) !== null;
        return self::$relationMethodCache[$key] = $result;
    }

    /**
     * Build the Psalm Union type for the given aggregate suffix.
     *
     * Types match Laravel's raw database output before any model casts are applied.
     * Results are cached to avoid repeated allocation across analysis runs.
     *
     * @psalm-external-mutation-free
     */
    private static function buildTypeForSuffix(string $suffix): Union
    {
        if (isset(self::$typeCache[$suffix])) {
            return self::$typeCache[$suffix];
        }

        $type = match ($suffix) {
            'count'      => new Union([new TInt()]),
            'exists'     => new Union([new TBool()]),
            'min', 'max' => new Union([new TString(), new TNull()]),
            'sum', 'avg' => new Union([new TNumericString(), new TNull()]),
            default      => throw new \LogicException("Unexpected aggregate suffix: {$suffix}"),
        };

        return self::$typeCache[$suffix] = $type;
    }

    /**
     * Convert a snake_case string to camelCase.
     *
     * `work_orders` → `workOrders`
     *
     * @psalm-pure
     */
    private static function snakeToCamelCase(string $value): string
    {
        return \lcfirst(\str_replace('_', '', \ucwords($value, '_')));
    }

    /**
     * Check whether the user has declared a @property PHPDoc for this property.
     * If so, we defer to their declaration instead of providing an aggregate type.
     *
     * @psalm-external-mutation-free
     */
    private static function hasUserPseudoProperty(Codebase $codebase, string $fqClasslikeName, string $propertyName): bool
    {
        $key = $fqClasslikeName . '::$' . $propertyName;

        if (\array_key_exists($key, self::$pseudoPropertyCache)) {
            return self::$pseudoPropertyCache[$key];
        }

        if (! $codebase->classlike_storage_provider->has($fqClasslikeName)) {
            return self::$pseudoPropertyCache[$key] = false;
        }

        $classStorage = $codebase->classlike_storage_provider->get($fqClasslikeName);
        $result = isset($classStorage->pseudo_property_get_types['$' . $propertyName]);
        return self::$pseudoPropertyCache[$key] = $result;
    }
}
