name: Psalm

on:
  push:
    paths:
      - '**.php'
      - 'psalm*'
      - 'composer.json'
      - '.github/workflows/psalm.yml'
  pull_request:
    paths:
      - '**.php'
      - 'psalm*'
      - 'composer.json'
      - '.github/workflows/psalm.yml'

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Block all outbound calls except allowlist)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            packagist.org:443
            release-assets.githubusercontent.com:443
            repo.packagist.org:443
            shepherd.dev:443

      - name: Silence Canonical telemetry units (apt-news, esm-cache, motd-news, ua-timer)
        run: sudo systemctl mask --now apt-news esm-cache motd-news ua-timer.timer

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install composer dependencies
        run: composer install -n --prefer-dist

      - name: Run Psalm
        run: ./vendor/bin/psalm --threads=2 --output-format=github --shepherd
