name: Release Drafter

on:
  workflow_dispatch:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # required to draft releases
      pull-requests: read   # required for autolabeler input
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@c2e2804cc59f45f57076a99af580d0fedb697927 # v7
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: config/release-drafter.yml
          token: ${{ secrets.GITHUB_TOKEN }}
